import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    /*boton: {
        backgroundColor: "#5865F2",
        padding: 10,
        marginLeft: 10,
        marginRight: 10,
        marginTop: 20,
        borderRadius: 5,
    }*/
    TextoB: {
        color: "white",
        fontSize: 18,
    },
    img: {
        height: 30,
        width: 30,
        marginRight: 10,
    },
    estiloCaja: {
        height: 70,
        borderColor: "#000",
        borderWidth: 2,
        borderRadius: 8,
        margin: 5,
        alignItems: "flex-end",
        justifyContent: "center",
        padding: 10,
    },
    TCaja: {
        fontSize: 30,
    },
    calcContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    textoB: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "bold",
        textAlign: "center",
    },
    container: {
        flex: 1,
        alignItems: "strech",
    },
    encabezado: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        paddingTop: 20,
    },
    cuerpo: {
        flex: 12,
        backgroundColor: "#cdc",
    },
    pie: {
        flex: 2,
        justifyContent: "start",
        flexDirection: "row",
        backgroundColor: "#000000",
    },
    textF: {
        fontSize: 20,
        textShadowColor: "#cdc",
        textShadowRadius: 20,
        fontWeight: "bold",
        textAlign: "center",
        color: "#fff",
        margin: 2,
    },
    textL: {
        fontSize: 12,
        fontWeight: "bold",
        textAlign: "center",
        color: "#A0A0A0",
    },
    textL2: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#A0A0A0",
    },
    images: {
        resizeMode: "cover",
        width: 40,
        height: 40,
    },
    link: {
        fontSize: 12,
        marginLeft: 10,
        marginTop: 5,
        fontWeight: "bold",
        color: "#3D8CB5",
    },
    inputs: {
        backgroundColor: "#32323C",
        marginBottom: 10,
        marginTop: 2,
        marginLeft: 10,
        marginRight: 10,
        height: 48,
        borderRadius: 5,
        fontSize: 15,
        padding: 15,
        color: "#fff",
        fontWeight: "bold",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    input: {
        color: "#fff",
        width: 280,
        fontWeight: "bold",
    },
    icon: {
        marginLeft: 10,
    },
    //ESTILOS PARA LA CALCULADORA
    container2: {
        paddingRight: 5,
        paddingLeft: 5,
        marginTop: 60,
        width: "100%",
        height: "100%",
        alignItems: "center",
    },
    containerB: {
        width: "100%",
        height: "100%",
    },
    result: {
        marginLeft: 5,
        marginRight: 5,
        padding: 10,
        height: 70,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "flex-end",
        backgroundColor: "#3b3a3a",
    },
    resultText: {
        color: "#ffffff",
        fontSize: 30,
        fontWeight: "bold",
    },
    buttons: {
        display: "flex",
        flexDirection: "row",
        flexWrap: "wrap",
        marginTop: 30,
        gap: 3,
        justifyContent: "center",
        alignItems: "center",
    },
    button: {
        width: "23%",
        aspectRatio: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#3498db",
        borderRadius: 10,
        margin: 2,
    },
    buttonText: {
        color: "#ffffff",
        fontSize: 20,
    },
    //ESTILOS PARA LA PANTALLA API
    bgnd: {
        flex: 8,
        backgroundColor: "#8b0000",
        display: "flex",
        padding: 20,
    },
    conts: {
        width: "100%",
        padding: 15,
        backgroundColor: "#808080",
        borderWidth: 5,
        borderColor: "#cde",
        borderRadius: 20,
        display: "flex",
        alignItems: "center",
        flexGrow: 1,
    },
    header: {
        backgroundColor: "#333",
        flexDirection: "column",
        alignItems: "center",
        padding: 20,
    },
    footer:{
        backgroundColor: "#333",
        flexDirection: "row",
        justifyContent: "center",
        padding: 10,
    },
    imgScrn:{
        margin: 10,
        height: 300,
        width: 200,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: "#aaa",
    },
    scrText:{
        fontSize: 15,
        fontWeight: "bold",
        color: "#fff",
        margin: 6,
    }
});